#!/bin/bash

if [ ! -e /var/www/html/artisan ] && [ ! -e /var/www/html/public/index.php ]; then
  echo 'Create Laravel project'

  export COMPOSER_ALLOW_SUPERUSER=1
  composer show
  #composer create-project laravel/laravel /app -n --no-dev --prefer-dist
  composer create-project lariele/laravel-tall-boilerplate /var/www/html -n --no-dev --prefer-dist

  cd /var/www/html
  echo 'NPM install'
  npm install

  npm install sass

  chmod -R 775 /var/www/html/public
  chmod -R ugo+rw /var/www/html/public

  echo 'NPM Run build'
  npm run build

  chmod -R 775 /var/www/html/public
  chmod -R ugo+rw /var/www/html/public

  php artisan migrate

  echo "Set owner to storage"
  chmod -R 775 /var/www/html/storage
  chmod -R ugo+rw /var/www/html/storage
  echo "Storage owner updated"
fi

exec "$@"
