#!/bin/bash

if [ ! -e app/artisan ] && [ ! -e app/public/index.php ]; then
  echo 'Create Laravel project'

  export COMPOSER_ALLOW_SUPERUSER=1
  composer show
  #composer create-project laravel/laravel /app -n --no-dev --prefer-dist
  composer create-project lariele/laravel-tall-boilerplate /app -n --no-dev --prefer-dist

  cd /app
  echo 'NPM install'
  npm install

  npm install sass

  chmod -R 775 /app/public
  chmod -R ugo+rw /app/public

  echo 'NPM Run build'
  npm run build

  chmod -R 775 /app/public
  chmod -R ugo+rw /app/public

  php artisan migrate

  echo "Set owner to storage"
  chmod -R 775 /app/storage
  chmod -R ugo+rw /app/storage
  echo "Storage owner updated"
fi

exec "$@"
